credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: "abc"
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: "abc"
    roibert:
      email: roibert@gmail.com
      name: Roibert Estrada
      password: "abc"
cookie:
  expiry_days: 0
  key: random_signature_key # Must be string
  name: random_cookie_name